### ISSUE TITLE
Allow Selection of Types to export instead of exporting everything, always

### ISSUE THREAD

**Issue by timfenton-shaw** [Kentico/kontent-google-sheets-add-on#17]
Currently, when using the new(ish) export functionality it exports everything, always. I would like to have the ability to select the content types that I will export. One of our projects is so large that it times out the export feature and i think being able to select which content types we want to export would help that a ton.

**Comment by ileshmistry** [comment]
@kentico-ericd 
I would like this too, I agree with @timfenton-shaw that currently there are lots of components (Content Types) in a project, and it doesn't go through the full process for me, it shows an error.

I guess being able to select a content type ourselves, will allow us to focus on only the ones we need exporting

**Comment by adolina-shaw** [comment]
Is there any update on this issue? This feature would be greatly appreciated!

**Comment by ileshmistry** [comment]
@kentico-ericd Not sure if you have an update on this? As it would be really beneficial for us to export a single Content Types content and then use this to form a template to import back into Kontent

**Comment by kentico-ericd** [comment]
@timfenton-shaw @ileshmistry @adolina-shaw 
Apologies for the long wait, I've joined the Xperience Integration team so I have been busy! I released [v65](https://github.com/Kentico/kontent-google-sheets-add-on/releases/tag/v65) which changes the behavior to only export a single content type at a time. This means a bit more clicking, but hopefully that takes care of timeouts. Let me know if you have any feedback on it!

**Comment by adunderground** [comment]
@adolina-shaw @kentico-ericd  Hey Eric, thanks for the update. I can see the content type dropdown now. However when I click Export I still get the "Add-on error" message. I also verified that this content type has 40 rows, unlike some other content types that we use that have around 1k. I also reinstalled the add-on and updated the API keys as a precaution. 

Here's the screenshot of my network tab – maybe it would come in handy when you're looking into this.

![image](https://user-images.githubusercontent.com/55853692/173628528-29ff68ad-624e-4263-a5b9-49d2a40f36c6.png)

**Comment by kentico-ericd** [comment]
@adunderground
I've found some errors in Google App Scripts mentioning "Limit Exceeded: URLFetch header size." After some testing it seems that under some circumstances, the `continuation_token` used by the Management API items feed can become very large and exceed [the 8KB limit](https://developers.google.com/apps-script/guides/services/quotas#current_limitations) for request headers. I'll keep digging!

**Comment by kentico-ericd** [comment]
@adunderground I spoke to developers on the Kontent team and unfortunately it is expected that the `continuation_token` exceeds 8KB. This is not a problem for standard HTTP requests as there's no header size limit- 8KB is a limit imposed by Google App Scripts. So at the moment, it seems that the Management API /items endpoint is not entirely compatible with Google Apps Script.

In the future, it's possible that the add-on could be re-worked to not use the /items endpoint. If you're interested, I would recommend creating a separate GitHub issue for tracking that solution. Thank you!
